Migrate generate_signature method
oppia/oppia-ml pull request #40
Opened 2021-05-15 17:26 UTC by rohitkatlaa

## Overview

1. This PR fixes [#12671](https://github.com/oppia/oppia/issues/12671) in oppia main repo.
2. This PR does the following: This PR modifies the generate_signature in the classifier_services so that it works in both python2 and python3. 

Note that there is an equivalent PR in the Oppia repository so both the PRs must be merged simultaneously.

2021-05-15 20:42 UTC, vojtechjelinek requested changes
Thanks! Left a few comments.

2021-05-15 20:42 UTC, vojtechjelinek commented on core/domain/remote_access_services.py
> +    key = _get_shared_secret().encode()
```suggestion
    key = _get_shared_secret().encode('utf-8')
```

2021-05-15 20:42 UTC, vojtechjelinek commented on core/domain/remote_access_services.py
> +        'message': _get_vm_id().encode(),
```suggestion
        'vm_id': _get_vm_id().encode('utf-8'),
        'message': _get_vm_id().encode('utf-8'),
```

2021-05-15 20:42 UTC, vojtechjelinek commented on core/domain/remote_access_services.py
> +    signature = generate_signature(message, payload.vm_id)
```suggestion
    payload.vm_id = _get_vm_id().encode('utf-8')
    message = payload.job_result.SerializeToString().encode('utf-8')
    signature = generate_signature(message, payload.vm_id)
```

2021-05-15 20:42 UTC, vojtechjelinek commented on core/domain/remote_access_services_test.py
> +                message.encode(), vm_id.encode())
```suggestion
                message.encode('utf-8'), vm_id.encode('utf-8'))
```

2021-05-16 11:27 UTC, rohitkatlaa commented on core/domain/remote_access_services.py
> +    key = _get_shared_secret().encode()
Done.

2021-05-16 11:27 UTC, rohitkatlaa commented on core/domain/remote_access_services.py
> +        'message': _get_vm_id().encode(),
Done.

2021-05-16 11:27 UTC, rohitkatlaa commented on core/domain/remote_access_services.py
> +    signature = generate_signature(message, payload.vm_id)
Done.

2021-05-16 11:27 UTC, rohitkatlaa commented on core/domain/remote_access_services_test.py
> +                message.encode(), vm_id.encode())
Done.

2021-05-22 14:41 UTC, vojtechjelinek approved these changes
LGTM!

2021-05-22 18:11 UTC, seanlip approved these changes
Hm, I think we'll need to redo some of this stuff when we move this repo to Python 3, but let's just bring it in for now so at least there's consistency. Thanks @rohitkatlaa!

2021-05-22 18:11 UTC, merged